# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress GitHub Actions
'on':
  push:
    branches:
      - 'master'
  pull_request:
    branches:
     - 'master'
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          'node:version': '14'
      - name: Install dependencies
        working-directory: ./Leaderboard 
        run: npm install --package-lock
      - name: Cypress run
        working-directory: ./Leaderboard
